#!/bin/bash
set -eux
DIR="$(dirname `readlink -f $0`)"
TARGET="${DIR}/deployment_scripts/puppet/modules/onos/files"
packages=packages.tar.gz
packages_url=http://205.177.226.235:9999/packages.tar.gz
cd $TARGET
if [ ! -f "onos-1.3.0.tar.gz" ]; then
  wget --no-cookies $packages_url -P $TARGET
  tar zxf packages.tar.gz -C $TARGET
  mv packages/onos/* ./
  rm -rf packages.tar.gz
  rm -rf packages
fi
