#!/bin/bash
set -eux
DIR="$(dirname `readlink -f $0`)"
TARGET="${DIR}/deployment_scripts/puppet/modules/onos/files"
ONOS_TAR=${ONOS_TAR:-onos-1.3.0.tar.gz}

packages=${packages:-http://58.251.166.184:9999/OPNFV/Compass4nfv/cache/packages.tar.gz}
cd $TARGET
if [ ! -f "$ONOS_TAR" ]; then
  wget --no-cookies $packages -P $TARGET
fi

tar zxf packages.tar.gz -C $TARGET
mv packages/onos/* ./
rm -rf packages.tar.gz
rm -rf packages